### ISSUE TITLE
LeTOH protocol documentation

### ISSUE THREAD

**Issue by datakurre** [kimmoli/letoh-app#2]
@kimmoli Would you have time to better document, how to control LeTOH over I2C? What bytes to send to which addresses, etc. I'm playing with Python and LeTOH, but I since I'm don't fully understand the protocol from letoh-app sources, I'm able to only shut down some of the leds (from Python) :)

**Comment by kimmoli** [comment]
will do

**Comment by kimmoli** [comment]
Hope this helps
aee0abbc821aa3f411a66dd4a541d1d1ce72e6a7

**Comment by datakurre** [comment]
@kimmoli Cool! Thanks. This seemed to cover all the magic in code :)

**Comment by datakurre** [comment]
Just FYI that I got LeTOH working from Python. Maybe I'll learn RPM packaging, after I find time to make it do something useful and robust.

https://github.com/datakurre/harbour-pyletoh/blob/master/qml/app.py
